markdown: rdiscount 
permalink: /:year/:month/:day/:title 
title: junzhou
url: http://zjun87.hp88.net
subscribe: http://zjun87.hp88.net
exclude: [ README.md, newpost.rb ]
domain: http://zjun87.hp88.net
author: junzhou
email:zjun87@gmail.com
auto: true
twitterID: ztpala
googleAnalyticsID: UA-5531632-1
disqusShortname: ztpala